# Generated by Django 3.0.6 on 2020-07-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shipping_price', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Shipping To',
            },
        ),
    ]
